<template>
  <ToolLayout>
    <section class="section">
      <h1>HTML Minifier <span>(v4.0.0)</span></h1>
      <textarea id="input" rows="8" cols="40" />
      <div class="minify-button">
        <button id="minify-btn" type="button">
          Minify
        </button>
      </div>
      <textarea id="output" rows="8" cols="40" />

      <p id="stats" />
      <div id="options">
        <ul>
          <li>
            <input id="caseSensitive" type="checkbox">
            <label for="caseSensitive">
              区分大小写
            </label>
            <span class="quiet short">
              以区分大小写的方式处理属性（对自定义 HTML 标记很有用）
            </span>
          </li>
          <li>
            <input id="collapseBooleanAttributes" type="checkbox">
            <label for="collapseBooleanAttributes">
              折叠布尔属性
            </label>
            <span class="quiet short">
              从布尔属性中省略属性值
            </span>
          </li>
          <li>
            <input id="collapseWhitespace" type="checkbox">
            <label for="collapseWhitespace">
              折叠空格
            </label>
            <span class="quiet short">
              折叠文档树中文本节点的空格
            </span>
          </li>
          <li>
            <input id="collapseInlineTagWhitespace" type="checkbox">
            <label for="collapseInlineTagWhitespace" class="unsafe">
              折叠内联标签空格
            </label>
            <span class="quiet short">
              折叠时不要在 display：inline; 元素之间留任何空格。 必须与 "折叠空格" 结合使用
            </span>
          </li>
          <li>
            <input id="conservativeCollapse" type="checkbox">
            <label for="conservativeCollapse">
              保守折叠
            </label>
            <span class="quiet short">
              始终折叠到 1 个空格（切勿将其完全删除）。 必须与 "折叠空格" 结合使用
            </span>
          </li>
          <li>
            <input id="preserveLineBreaks" type="checkbox">
            <label for="preserveLineBreaks">
              保留换行符
            </label>
            <span class="quiet short">
              当标记之间的空格包含换行符时，始终折叠到 1 个换行符（永远不要完全删除它）。 必须与 "折叠空格" 结合使用
            </span>
          </li>
          <li>
            <input id="decodeEntities" type="checkbox">
            <label for="decodeEntities">
              解码实体字符
            </label>
            <span class="quiet short">
              尽可能使用直接的 Unicode 字符
            </span>
          </li>
          <li>
            <input id="html5" type="checkbox">
            <label for="html5">
              HTML5
            </label>
            <span class="quiet short">
              根据 HTML5 规范解析输入
            </span>
          </li>
          <li>
            <input id="includeAutoGeneratedTags" type="checkbox">
            <label for="includeAutoGeneratedTags">
              包括自动生成的标签
            </label>
            <span class="quiet short">
              插入 HTML 解析器生成的标签
            </span>
          </li>
          <li>
            <input id="keepClosingSlash" type="checkbox">
            <label for="keepClosingSlash">
              保持标签闭合
            </label>
            <span class="quiet short">
              在单例元素上保留尾部斜杠
            </span>
          </li>
          <li>
            <label for="maxLineLength">
              每行最大字符数
            </label>
            <input id="maxLineLength" type="text">
            <span class="quiet short">
              压缩输出将在有效的 HTML 拆分点处用换行符拆分
            </span>
          </li>
          <li>
            <input id="minifyCSS" type="checkbox">
            <label for="minifyCSS">
              缩小 CSS
            </label>
            <span class="quiet short">
              缩小样式元素和样式属性中的 CSS（使用 clean-css）
            </span>
          </li>
          <li>
            <input id="minifyJS" type="checkbox">
            <label for="minifyJS">
              缩小 JavaScript
            </label>
            <span class="quiet short">
              缩小脚本元素和事件属性中的 JavaScript（使用 UglifyJS）
            </span>
          </li>
          <li>
            <label for="minifyURLs">
              缩小 URL
            </label>
            <input id="minifyURLs" type="text">
            <span class="quiet short">
              缩小URL中的各种属性（使用 relateurl）
            </span>
          </li>
          <li>
            <input id="preventAttributesEscaping" type="checkbox">
            <label for="preventAttributesEscaping" class="unsafe">
              防止属性转义
            </label>
            <span class="quiet short">
              防止属性值转义
            </span>
          </li>
          <li>
            <input id="processConditionalComments" type="checkbox">
            <label for="processConditionalComments">
              处理条件注释
            </label>
            <span class="quiet short">
              通过压缩器处理条件注释的内容
            </span>
          </li>
          <li>
            <label for="processScripts">
              处理脚本
            </label>
            <input id="processScripts" type="text" value="text/html">
            <span class="quiet short">
              逗号分隔的字符串，对应于要通过压缩器处理的脚本元素类型（例如 text/ng-template、text/x-handlebars-template）
            </span>
          </li>
          <li>
            <label for="quoteCharacter">
              引号字符
            </label>
            <input id="quoteCharacter" type="text">
            <span class="quiet short">
              用于属性值的引号类型（' 或 “）
            </span>
          </li>
          <li>
            <input id="removeAttributeQuotes" type="checkbox">
            <label for="removeAttributeQuotes">
              删除属性引号
            </label>
            <span class="quiet short">
              尽可能删除属性周围的引号
            </span>
          </li>
          <li>
            <input id="removeComments" type="checkbox">
            <label for="removeComments">
              删除注释
            </label>
            <span class="quiet short">
              删除 HTML 注释
            </span>
          </li>
          <li>
            <input id="removeEmptyAttributes" type="checkbox">
            <label for="removeEmptyAttributes">
              删除空属性
            </label>
            <span class="quiet short">
              删除所有仅包含空格值的属性
            </span>
          </li>
          <li>
            <input id="removeEmptyElements" type="checkbox">
            <label for="removeEmptyElements" class="unsafe">
              删除空元素
            </label>
            <span class="quiet short">
              删除所有内容为空的元素
            </span>
          </li>
          <li>
            <input id="removeOptionalTags" type="checkbox">
            <label for="removeOptionalTags">
              删除可选标签
            </label>
          </li>
          <li>
            <input id="removeRedundantAttributes" type="checkbox">
            <label for="removeRedundantAttributes">
              删除冗余属性
            </label>
            <span class="quiet short">
              当值与默认值匹配时删除属性
            </span>
          </li>
          <li>
            <input id="removeScriptTypeAttributes" type="checkbox">
            <label for="removeScriptTypeAttributes">
              删除脚本类型属性
            </label>
            <span class="quiet short">
              从脚本标记中删除 type=“text/javascript”。 其他类型属性值保持不变
            </span>
          </li>
          <li>
            <input id="removeStyleLinkTypeAttributes" type="checkbox">
            <label for="removeStyleLinkTypeAttributes">
              删除样式链接类型属性
            </label>
            <span class="quiet short">
              从样式和链接标记中删除 type=“text/css”。 其他类型属性值保持不变
            </span>
          </li>
          <li>
            <input id="removeTagWhitespace" type="checkbox">
            <label for="removeTagWhitespace" class="unsafe">
              删除标签空格
            </label>
            <span class="quiet short">
              尽可能删除属性之间的空格。请注意，这将导致无效的 HTML！
            </span>
          </li>
          <li>
            <input id="sortAttributes" type="checkbox">
            <label for="sortAttributes" class="unsafe">
              对属性进行排序
            </label>
            <span class="quiet short">
              按频率对属性进行排序
            </span>
          </li>
          <li>
            <input id="sortClassName" type="checkbox">
            <label for="sortClassName" class="unsafe">
              对类名进行排序
            </label>
            <span class="quiet short">
              按频率对样式类进行排序
            </span>
          </li>
          <li>
            <input id="trimCustomFragments" type="checkbox">
            <label for="trimCustomFragments">
              修剪自定义片段周围的空白
            </label>
            <span class="quiet short">
              修剪 ignoreCustomFragments 周围的空白
            </span>
          </li>
          <li>
            <input id="useShortDoctype" type="checkbox">
            <label for="useShortDoctype">
              使用短文档类型
            </label>
            <span class="quiet short">
              将文档类型替换为短文档类型 （HTML5 doctype） 文档类型
            </span>
          </li>
        </ul>
        <div class="controls">
          <span>Select:</span>
          <a id="select-all" href="#">All</a>,
          <a id="select-none" href="#">None</a>,
          <a id="select-defaults" href="#">Reset</a>
        </div>
      </div>
    </section>
  </ToolLayout>
</template>

<script setup lang="ts">
import beautify from 'js-beautify'

useHead({
  script: [{ src: '/assets/js/html-minify/index.js' }]
})

const input = ref('')

let minify = (function () {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const minify = require('html-minifier').minify
  return function (value, options, callback, errorback) {
    options.log = function (message) {
      console.log(message)
    }
    let minified
    try {
      minified = minify(value, options)
    } catch (err) {
      return errorback(err)
    }
    callback(minified)
  }
})()
if (typeof Worker === 'function') {
  const worker = new Worker('assets/js/html-minify/worker.js')
  worker.onmessage = function () {
    minify = function (value, options, callback, errorback) {
      worker.onmessage = function (event) {
        const data = event.data
        if (data.error) {
          errorback(data.error)
        } else {
          callback(data)
        }
      }
      worker.postMessage({
        value,
        options
      })
    }
  }
}

function byId (id) {
  return document.getElementById(id)
}

function escapeHTML (str) {
  return (str + '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function forEachOption (fn) {
  [].forEach.call(byId('options').getElementsByTagName('input'), fn)
}

function getOptions () {
  const options = {}
  forEachOption(function (element) {
    const key = element.id
    let value
    if (element.type === 'checkbox') {
      value = element.checked
    } else {
      value = element.value.replace(/^\s+|\s+$/, '')
      if (!value) {
        return
      }
    }
    switch (key) {
      case 'maxLineLength':
        value = parseInt(value)
        break
      case 'processScripts':
        value = value.split(/\s*,\s*/)
    }
    options[key] = value
  })
  return options
}

function commify (str) {
  return String(str)
    .split('').reverse().join('')
    .replace(/(...)(?!$)/g, '$1,')
    .split('').reverse().join('')
}

byId('minify-btn').onclick = function () {
  byId('minify-btn').disabled = true
  const originalValue = byId('input').value
  minify(originalValue, getOptions(), function (minifiedValue) {
    const diff = originalValue.length - minifiedValue.length
    const savings = originalValue.length ? (100 * diff / originalValue.length).toFixed(2) : 0

    byId('output').value = minifiedValue

    byId('stats').innerHTML =
        '<span class="success">' +
          'Original size: <strong>' + commify(originalValue.length) + '</strong>' +
          '. Minified size: <strong>' + commify(minifiedValue.length) + '</strong>' +
          '. Savings: <strong>' + commify(diff) + ' (' + savings + '%)</strong>.' +
        '</span>'
    byId('minify-btn').disabled = false
  }, function (err) {
    byId('output').value = ''
    byId('stats').innerHTML = '<span class="failure">' + escapeHTML(err) + '</span>'
    byId('minify-btn').disabled = false
  })
}

byId('select-all').onclick = function () {
  forEachOption(function (element) {
    if (element.type === 'checkbox') {
      element.checked = true
    }
  })
  return false
}

byId('select-none').onclick = function () {
  forEachOption(function (element) {
    if (element.type === 'checkbox') {
      element.checked = false
    } else {
      element.value = ''
    }
  })
  return false
}

const defaultOptions = getOptions()
byId('select-defaults').onclick = function () {
  for (const key in defaultOptions) {
    const element = byId(key)
    element[element.type === 'checkbox' ? 'checked' : 'value'] = defaultOptions[key]
  }
  return false
}

function handleBeautify () {
  return beautify(input.value, {})
}
</script>
