<template>
  <ToolLayout>
    <section class="section html">
      <ul class="html-config">
        <el-button-group class="html-config-fast">
          <el-button type="primary" @click="selectAll">
            全选
          </el-button>
          <el-button type="primary" @click="handleClear">
            清空
          </el-button>
          <el-button type="primary" @click="handleReset">
            重置
          </el-button>
        </el-button-group>
        <li v-for="item in optionsList" :key="item.value">
          <template v-if="item.type === 'input'">
            <span class="html-config__name" :title="item.description">{{ item.name }}：</span>
            <el-input v-model="options[item.value]" />
          </template>
          <el-checkbox v-else v-model="options[item.value]">
            <span :title="item.description">{{ item.name }}</span>
          </el-checkbox>
        </li>
      </ul>
      <div class="html-editor">
        <CodeEditor v-model:code="input" class="code-editor" lang="html" :height="550" />
        <el-space :size="16" style="margin-bottom: 16px;">
          <el-button type="primary" @click="handleBeautify">
            美化
          </el-button>
          <el-button type="primary" @click="handleMinify">
            压缩
          </el-button>
        </el-space>
        <CodeEditor v-model:code="output" class="code-editor" lang="html" :height="550" />
        <CopyButton :text="output" />
      </div>
    </section>
  </ToolLayout>
</template>

<script setup lang="ts">
import beautify from 'js-beautify'

definePageMeta({
  title: 'HTML格式化',
  description: '支持HTML代码压缩、美化。'
})

const defaultConfig: Record<string, any> = {
  collapseBooleanAttributes: true,
  collapseWhitespace: true,
  decodeEntities: true,
  html5: true,
  minifyCSS: true,
  minifyJS: true,
  processConditionalComments: true,
  processScripts: 'text/html',
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: true,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: true,
  sortAttributes: true,
  sortClassName: true,
  trimCustomFragments: true,
  useShortDoctype: true
}

const input = ref('')
const output = ref('')
const options = ref<Record<string, any>>({ ...defaultConfig })
const optionsList = reactive([
  {
    name: '区分大小写',
    value: 'caseSensitive',
    description: '以区分大小写的方式处理属性（对自定义 HTML 标记很有用）'
  },
  {
    name: '折叠布尔属性',
    value: 'collapseBooleanAttributes',
    description: '从布尔属性中省略属性值'
  },
  {
    name: '折叠空格',
    value: 'collapseWhitespace',
    description: '折叠文档树中文本节点的空格'
  },
  {
    name: '折叠内联标签空格',
    value: 'collapseInlineTagWhitespace',
    description: '折叠时不要在 display：inline; 元素之间留任何空格。 必须与 "折叠空格" 结合使用'
  },
  {
    name: '保守折叠',
    value: 'conservativeCollapse',
    description: '始终折叠到 1 个空格（切勿将其完全删除）。 必须与 "折叠空格" 结合使用'
  },
  {
    name: '保留换行符',
    value: 'preserveLineBreaks',
    description: '当标记之间的空格包含换行符时，始终折叠到 1 个换行符（永远不要完全删除它）。 必须与 "折叠空格" 结合使用'
  },
  {
    name: '解码实体字符',
    value: 'decodeEntities',
    description: '尽可能使用直接的 Unicode 字符'
  },
  {
    name: 'HTML5',
    value: 'html5',
    description: '根据 HTML5 规范解析输入'
  },
  {
    name: '包括自动生成的标签',
    value: 'includeAutoGeneratedTags',
    description: '插入 HTML 解析器生成的标签'
  },
  {
    name: '保持标签闭合',
    value: 'keepClosingSlash',
    description: '在单例元素上保留尾部斜杠'
  },
  {
    name: '每行最大字符数',
    value: 'maxLineLength',
    description: '压缩输出将在有效的 HTML 拆分点处用换行符拆分',
    type: 'input'
  },
  {
    name: '缩小 CSS',
    value: 'minifyCSS',
    description: '缩小样式元素和样式属性中的 CSS（使用 clean-css）'
  },
  {
    name: '缩小 JavaScript',
    value: 'minifyJS',
    description: '缩小脚本元素和事件属性中的 JavaScript（使用 UglifyJS）'
  },
  {
    name: '缩小 URL',
    value: 'minifyURLs',
    description: '缩小URL中的各种属性（使用 relateurl）',
    type: 'input'
  },
  {
    name: '防止属性转义',
    value: 'preventAttributesEscaping',
    description: '防止属性值转义'
  },
  {
    name: '处理条件注释',
    value: 'processConditionalComments',
    description: '通过压缩器处理条件注释的内容'
  },
  {
    name: '处理脚本',
    value: 'processScripts',
    description: '逗号分隔的字符串，对应于要通过压缩器处理的脚本元素类型（例如 text/ng-template、text/x-handlebars-template）',
    type: 'input'
  },
  {
    name: '引号字符',
    value: 'quoteCharacter',
    description: "用于属性值的引号类型（' 或 “）",
    type: 'input'
  },
  {
    name: '删除属性引号',
    value: 'removeAttributeQuotes',
    description: '尽可能删除属性周围的引号'
  },
  {
    name: '删除注释',
    value: 'removeComments',
    description: '删除 HTML 注释'
  },
  {
    name: '删除空属性',
    value: 'removeEmptyAttributes',
    description: '删除所有仅包含空格值的属性'
  },
  {
    name: '删除空元素',
    value: 'removeEmptyElements',
    description: '删除所有内容为空的元素'
  },
  {
    name: '删除可选标签',
    value: 'removeOptionalTags',
    description: '删除可选标签'
  },
  {
    name: '删除冗余属性',
    value: 'removeRedundantAttributes',
    description: '当值与默认值匹配时删除属性'
  },
  {
    name: '删除脚本类型属性',
    value: 'removeScriptTypeAttributes',
    description: '从脚本标记中删除 type=“text/javascript”。 其他类型属性值保持不变'
  },
  {
    name: '删除样式链接类型属性',
    value: 'removeStyleLinkTypeAttributes',
    description: '从样式和链接标记中删除 type=“text/css”。 其他类型属性值保持不变'
  },
  {
    name: '删除标签空格',
    value: 'removeTagWhitespace',
    description: '尽可能删除属性之间的空格。请注意，这将导致无效的 HTML！'
  },
  {
    name: '对属性进行排序',
    value: 'sortAttributes',
    description: '按频率对属性进行排序'
  },
  {
    name: '对类名进行排序',
    value: 'sortClassName',
    description: '按频率对样式类进行排序'
  },
  {
    name: '修剪自定义片段周围的空白',
    value: 'trimCustomFragments',
    description: '修剪 ignoreCustomFragments 周围的空白'
  },
  {
    name: '使用短文档类型',
    value: 'useShortDoctype',
    description: '将文档类型替换为短文档类型 （HTML5 doctype） 文档类型'
  }
])

function handleClear () {
  options.value = {}
}
function selectAll () {
  const result = { ...defaultConfig }
  optionsList.forEach((item) => {
    if (!item.type) {
      result[item.value] = true
    }
  })
  options.value = result
}
function handleReset () {
  options.value = { ...defaultConfig }
}

let minify: any
if (typeof Worker === 'function') {
  const worker = new Worker('/assets/js/html-minify/worker.js')
  worker.onmessage = function () {
    minify = function (value: string, options: any, callback: Function, errorback?: Function) {
      worker.onmessage = function (event) {
        const data = event.data
        if (data.error && errorback) {
          errorback(data.error)
        } else {
          callback(data)
        }
      }
      worker.postMessage({
        value,
        options
      })
    }
  }
}

function handleMinify () {
  minify(input.value, {
    ...options.value
  }, function (minifiedValue: string) {
    output.value = minifiedValue
  })
}

function handleBeautify () {
  output.value = beautify.html(input.value, {})
}
</script>

<style lang="scss" scoped>
.html {
  display: flex;
  gap: 16px;

  &-config {
    width: 256px;

    &-fast{
      margin-bottom: 12px;
    }

    &__name {
      display: inline-block;
      margin-bottom: 6px;
      color: var(--el-text-color-regular);
      font-size: 14px;
    }

    .el-input {
      margin-bottom: 6px;
    }
  }

  &-editor {
    flex: 1;
  }

  .code-editor :deep(.cm-editor) {
    margin-bottom: 16px;
  }
}
</style>
